# Generated by Django 4.2.7 on 2025-12-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
