# Generated by Django 4.2.7 on 2025-12-25 15:42

from django.db import migrations
import secrets


def generate_public_id():
    """Generate a unique random public ID"""
    return secrets.token_urlsafe(24)  # 32 characters when URL-safe encoded


def populate_public_ids(apps, schema_editor):
    """Populate public_id for all existing UserProfile instances"""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    for profile in UserProfile.objects.filter(public_id__isnull=True):
        # Generate unique public_id
        max_attempts = 10
        public_id = None
        for _ in range(max_attempts):
            candidate_id = generate_public_id()
            if not UserProfile.objects.filter(public_id=candidate_id).exists():
                public_id = candidate_id
                break
        
        if public_id:
            profile.public_id = public_id
            profile.save(update_fields=['public_id'])


def reverse_populate_public_ids(apps, schema_editor):
    """Reverse migration - set public_id to None"""
    UserProfile = apps.get_model('accounts', 'UserProfile')
    UserProfile.objects.all().update(public_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_public_id_field'),
    ]

    operations = [
        migrations.RunPython(populate_public_ids, reverse_populate_public_ids),
    ]
