# Generated by Django 4.2.7 on 2025-12-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_change_show_real_name_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='newsletter_subscription',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='preferred_cubase_version',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
