# Generated by Django 4.2.7 on 2025-12-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cubaseversion',
            options={'ordering': ['-major_version']},
        ),
        migrations.RemoveField(
            model_name='cubaseversion',
            name='minor_version',
        ),
        migrations.RemoveField(
            model_name='cubaseversion',
            name='patch_version',
        ),
    ]
