# Generated by Django 4.2.7 on 2025-12-22 23:40

from django.db import migrations, models
import macros.models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0003_add_xml_snippet_to_macro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keycommandsfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=macros.models.keycommands_upload_path),
        ),
    ]
