# Generated by Django 4.2.7 on 2025-12-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0004_make_file_field_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='macro',
            name='reference_snippet',
            field=models.TextField(blank=True),
        ),
    ]
