# Generated by Django 4.2.7 on 2025-12-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macros', '0005_add_reference_snippet_to_macro'),
    ]

    operations = [
        # First, add the new is_private field
        migrations.AddField(
            model_name='keycommandsfile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        # Invert values: is_public=True becomes is_private=False, is_public=False becomes is_private=True
        migrations.RunSQL(
            "UPDATE macros_keycommandsfile SET is_private = NOT is_public;",
            reverse_sql="UPDATE macros_keycommandsfile SET is_public = NOT is_private;",
        ),
        # Remove the old is_public field
        migrations.RemoveField(
            model_name='keycommandsfile',
            name='is_public',
        ),
    ]
